Sprint 2/step 1
RustemDiveev/yandex-praktikum-react pull request #3
Opened 2024-02-12 12:12 UTC by RustemDiveev

2024-02-12 13:42 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Используется контекст;

### **Но есть несколько замечаний, которые нужно исправить:**

- Нужно поправить верстку в соответствии с дизайном:

  - <https://disk.yandex.com/i/WAZKgpZYUNoO4w> - нужно стилизовать скролл (Это делается через css).
  - <https://disk.yandex.com/i/G-WzvbBF4PPBIA> - Скролл должен быть только у ингредиентов, булки должны оставаться на месте. А Также не хватает иконок слева от ингредиентов - <https://disk.yandex.com/i/V6In7dIC6wT_dQ>

- В запросе `/orders` нужно передавать объект с полем `ingredients`, поле `ingredients` это массив с `id` ингредиентов и булок. А также, нужно чтобы id у булок были в начале и в конце массива:;

- <https://disk.yandex.com/i/lrhatY3QOXx8SA> - нужно убрать синюю обводку у блоков, эта обводка на макете нужна только что бы сделать поясняющее описание к этому блоку;

### **Сделает код лучше:**

- При клике на таб скролить список ингредиентов к нужному разделу;

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2024-02-12 13:42 UTC, ArslanMustafin commented on react-burger/src/components/app/app.jsx
> +      const url = "https://norma.nomoreparties.space/api/ingredients"
**Надо исправить:**

вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`

2024-02-12 13:42 UTC, ArslanMustafin commented on react-burger/src/components/burger-constructor/burger-constructor.js
> +                "https://norma.nomoreparties.space/api/orders",
**Надо исправить:**

вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`

2024-02-12 13:42 UTC, ArslanMustafin commented on react-burger/src/components/burger-constructor/burger-constructor.js
> +                    body: ingredientsIds
**Надо исправить:**

вы должны передавать в запрос объект с ингредиентами, а не просто id ингредиентов. Также вы забыли  перевести данные в JSON формат. Ну и вам нужно обязательно указать  `headers: { 'Content-Type': 'application/json',},`, чтобы запрос отработал корректно.

Примерно так это должно выглядеть:
```js
const ingredientsIds = [bun._id, ...ingredients.map(elem => elem._id), bun._id];

const response = await fetch('https://norma.nomoreparties.space/api/orders', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
  },
  body: JSON.stringify({
    ingredients: ingredientsIds,
  }),
}).then(res => res.json())
```

2024-02-12 13:42 UTC, ArslanMustafin commented on react-burger/src/services/ingredientsContext.js
> +    totalPrice: undefined,
**Надо исправить:**

здесь и далее.

Вместо `undefined` лучше по возможности использовать другие falsy значения, например `null`, `''` или `0` . 

```js
ingredients: [],
bun: null, 
totalPrice: 0,
```

2024-02-12 13:42 UTC, ArslanMustafin commented on react-burger/src/services/orderContext.js
> +    orderNumber: undefined,
**Надо исправить:**

Здесь лучше использовать `null`, а не `undefined`,

2024-02-13 08:28 UTC, RustemDiveev commented on react-burger/src/components/app/app.jsx
> +      const url = "https://norma.nomoreparties.space/api/ingredients"
fixed

2024-02-13 08:48 UTC, RustemDiveev commented on react-burger/src/components/burger-constructor/burger-constructor.js
> +                "https://norma.nomoreparties.space/api/orders",
fixed

2024-02-13 08:54 UTC, RustemDiveev commented on react-burger/src/components/burger-constructor/burger-constructor.js
> +                    body: ingredientsIds
fixed

2024-02-13 08:56 UTC, RustemDiveev commented on react-burger/src/services/ingredientsContext.js
> +    totalPrice: undefined,
fixed

2024-02-13 08:57 UTC, RustemDiveev commented on react-burger/src/services/orderContext.js
> +    orderNumber: undefined,
fixed

2024-02-16 09:04 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

### **Сделает код лучше:**

- <https://disk.yandex.com/i/gn9PcOmQNGPZtg> - нужно стилизовать скролл (Это делается через css).

```css
::-webkit-scrollbar {
  width: 8px;
}

::-webkit-scrollbar-track {
  background: #2f2f37;
}

::-webkit-scrollbar-thumb {
  border: 3px solid #8585ad;
  background: #8585ad;
}
```

2024-02-16 09:04 UTC, ArslanMustafin commented on react-burger/src/components/burger-ingredients/burger-ingredients.js
> +          key={1}
**Можно лучше:**

здесь и далее

Тут вам не нужно использовать `key`, советую обратиться к документации:

<https://ru.legacy.reactjs.org/docs/lists-and-keys.html#keys>

2024-03-03 08:44 UTC, mikebars1995 reviewed
Здравствуйте. (**Нужно развернуть общий комментарий ↓**)

К сожалению, работу придется отклонить без потери итерации, так как по сслыке на пулл реквест находится проект без `redux`. Нужно выполнить проект в соответствии с заданием

2024-03-12 13:35 UTC, merged