Sprint 4/step 1
RustemDiveev/yandex-praktikum-react pull request #6
Opened 2024-04-09 18:47 UTC by RustemDiveev

2024-04-09 19:44 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Проект теперь типизирован;

### **Но есть несколько замечаний, которые нужно исправить:**

- Отметил замечания в коде;

- По чек-листу вы должно типизировать все утилитарные функции - файл `utils/request.js`. Если затрудняетесь, советую обратиться к наставнику или можете самостоятельно погуглить)

2024-04-09 19:44 UTC, ArslanMustafin commented on react-burger/src/components/burger-ingredients/burger-ingredients.tsx
> +  const handleTabClick = (e: string) => {
**Надо исправить:**

Поправьте тут название переменной, а то `e` не очень сюда подходит, и не говорит о том, что это за переменная.

2024-04-09 19:44 UTC, ArslanMustafin commented on react-burger/src/components/burger-ingredients/burger-ingredients.tsx
> +    return () => ingredientDomNode.removeEventListener("scroll", handleScroll as any)
Я думаю, тут вообще можно убрать useEffect, вы ведь уже используете `onScroll`, зачем вам дважды ставить прослушку?

2024-04-09 19:44 UTC, ArslanMustafin commented on react-burger/src/components/modal-overlay/modal-overlay.tsx
> +        <div className={styles.modal_overlay} onClick={() => closeModal()}>
**Можно лучше:**

Лучше вынести обработчик onClick в отдельную функцию.

2024-04-09 19:44 UTC, ArslanMustafin commented on react-burger/src/hooks/useForm.ts
> +const useForm = (inputValues: {[key: string]: any} = {}) => {
**Можно лучше/рекомендую исправить:**

тут можно воспользоваться дженериками, а также типом `React.ChangeEvent<HTMlInputElement>`.

```js
export function useForm<T>(inputValues: T) {

    const [values, setValues] = useState<T>(inputValues);

    const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
      const {value, name} = event.target;
      setValues({...values, [name]: value});
    };

    return {values, handleChange, setValues};

}

// как использовать:

type FormStateType = {
  name:string;
  password:string;
}

const initialFormState: FormStateType = {
  name: 'name',
  password: '',
}

const {...} = useForm<FormDataType>(initialFormState)
```

Вместо `React.FormEvent`, вам теперь нужно указывать `React.ChangeEvent<HTMLInputElement>`, чтобы ТС не ругался на хук.
Почему именно `React.ChangeEvent`:<https://stackoverflow.com/questions/40676343/typescript-input-onchange-event-target-value;>

2024-04-09 19:44 UTC, ArslanMustafin commented on react-burger/src/services/slices/constructorSlice.ts
> +                        uniqueId: uuidv4()
**Надо исправить:**

У вас до этого был правильный вариант, генерировать `uniqueId` нужно в `prepare`, т.к. 
редьюсер должен быть чистой функцией))

2024-04-09 19:44 UTC, ArslanMustafin commented on react-burger/src/services/slices/constructorSlice.ts
> +            }
**Можно лучше:**

А тут точно нужен `prepare`?

2024-04-09 19:44 UTC, ArslanMustafin commented on react-burger/src/utils/api.ts
> +const requestApi = async (url: string, options?: RequestInit) => {
**Надо исправить:**

По чек-листу вы должно типизировать все утилитарные функции, в том числен и запросы к серверу.
Типизировать запросы к серверу можно следующим образом:

```ts
type TServerResponse<T> = {
  success: boolean;
} & T;

const checkResponse = <T>(res: Response): Promise<T> => {
  return res.ok ? res.json() : res.json().then(err => Promise.reject(err));
};

const request = async <T>(endpoint: string, options?: RequestInit): Promise<T> => {
  return fetch(`${NORMA_API}${endpoint}`, options).then(res => checkResponse<T>(res));
};

type TIngredientsResponse = TServerResponse<{
  data: TIngredient[];
}>;

export const getIngredients = () => {
  return request<TIngredientsResponse>('/ingredients');
};
```

2024-04-10 16:14 UTC, RustemDiveev commented on react-burger/src/components/burger-ingredients/burger-ingredients.tsx
> +  const handleTabClick = (e: string) => {
fixed

2024-04-10 16:14 UTC, RustemDiveev commented on react-burger/src/components/burger-ingredients/burger-ingredients.tsx
> +    return () => ingredientDomNode.removeEventListener("scroll", handleScroll as any)
fixed

2024-04-10 16:16 UTC, RustemDiveev commented on react-burger/src/components/modal-overlay/modal-overlay.tsx
> +        <div className={styles.modal_overlay} onClick={() => closeModal()}>
fixed

2024-04-10 16:27 UTC, RustemDiveev commented on react-burger/src/hooks/useForm.ts
> +const useForm = (inputValues: {[key: string]: any} = {}) => {
fixed

2024-04-10 16:28 UTC, RustemDiveev commented on react-burger/src/services/slices/constructorSlice.ts
> +                        uniqueId: uuidv4()
fixed

2024-04-10 16:34 UTC, RustemDiveev commented on react-burger/src/services/slices/constructorSlice.ts
> +            }
Можно лучше, согласен, но не получается перебороть typescript, если просто убрать prepare

2024-04-11 14:48 UTC, RustemDiveev commented on react-burger/src/utils/api.ts
> +const requestApi = async (url: string, options?: RequestInit) => {
fixed

2024-04-12 09:00 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2024-04-12 09:00 UTC, ArslanMustafin commented on react-burger/src/services/slices/constructorSlice.ts
> +            // Если я убираю, то не понятно как избавиться от Typescript-ошибки, подскажите, пожалуйста
Вам нужно дополнительно поправить вызов экшена, а также чуть переписать сам редьюсер.

```js
ingredientDeleted: (state, action: PayloadAction<{ uniqueId: string }>) => {
  state.ingredients = state.ingredients.filter(
    ingredient => ingredient.uniqueId !== action.payload.uniqueId
  );
},
```

```js
const handleClose = (elem: IIngredient) => {
  return () => {
    dispatch(ingredientDeleted({ uniqueId: elem.uniqueId! }));
    dispatch(counterDecreased(elem._id));
  };
};
```

2024-04-12 09:00 UTC, ArslanMustafin commented on react-burger/src/components/profile-menu/profile-menu.tsx
> +    const response = await dispatch(logoutUser()).unwrap() as {success: boolean, message: string}
**Можно лучше:**

А почему бы сразу не типизировать `logoutUser`? как вы сделали это с остальными)))

2024-04-12 10:06 UTC, merged